# Generated by Django 2.2 on 2020-05-08 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='year_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
