# Generated by Django 2.2 on 2020-05-13 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20200508_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'ordering': ['-id']},
        ),
    ]
