# Generated by Django 2.2 on 2020-05-13 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_studentinfo_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
